services:
  standalone_mysql:
    image: mysql:latest
    container_name: standalone_mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - standalone_mysql_data:/var/lib/mysql
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d

volumes:
  standalone_mysql_data:
  db:
    driver: local
